services:
  app:
    build: .
    ports:
      - 3000:3000
    networks:
      - caddy
    restart: unless-stopped
    labels:
      caddy: alex-planner.projects.eevloeev.dev
      caddy.reverse_proxy: "{{upstreams 3000}}"

networks:
  caddy:
    external: true
